name: Build and push image

env:
  REPO: ghcr.io/turscar/hello-world

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build and push with podman
        shell: bash
        run: 
                    set -o xtrace
          read -r VERSION <VERSION
          GOOS=linux
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin
          podman build --env=GOOS --env=GOARCH=amd64 --tag=${REPO}/amd64:${VERSION} --file=Containerfile .
          podman push ${REPO}/amd64:${VERSION}
          podman build --env=GOOS --env=GOARCH=arm64 --tag=${REPO}/arm64:${VERSION} --file=Containerfile .
          podman push ${REPO}/arm64:${VERSION}
          podman manifest create ${REPO}:${VERSION}
          podman manifest add --arch=amd64 ${REPO}:${VERSION} ${REPO}/amd64:${VERSION}
          podman manifest add --arch=arm64 ${REPO}:${VERSION} ${REPO}/arm64:${VERSION}
          podman manifest push ${REPO}:${VERSION}
